### ISSUE TITLE
Problem running the examples

### ISSUE THREAD

**Issue by emmaPatagonia** [vackar/BayesISOLA#1]
Dear Vackar, I am trying to run BayesISOLA on my laptop (using Manjaro KDE) but I couldn't ran the examples.
When I ran the function data = BayesISOLA.process_data(..) it shows the following output and the message "Note: ..." go down into a eternal loop. Below is my screen output:

**_Pre-calculated grid point 14 was calculated with different parameters. Its coordinates differs, probably the shape of the grid was changed. File green/station.dat has different hash, probably station set was different. Source time function (file soutype.txt) was different. 
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
..._**

Do you know how can I fix it ?

kindly
Diego

**Comment by vackar** [comment]
Dear Diego,

it looks there are warning messages only.
Is there an output in "output/example_2_fdsnws/" directory? There should be log.txt and a few PNG images.
I will make the output more understandable and omit misleading warning messages in the next version.

Regards,
Jiri

**Comment by juliarnWu** [comment]
Dear Vackar,

I downloaded example_2_fdsnws.py on December 20 and ran the example on Windows 10. But the program has a bug in the "data=BayesISOLA.process_data(params=default)".  it shows the following output and the warning messages "..." go down into a eternal loop.  
(And a vignette, the function "os.mkdir" in laod_data.py changed to create the folder "output/example_2_fdsnws" for "os.makedirs")

there is an output in "output/example_2_fdsnws/" directory. There are log.txt(0-3kb) and log_green.txt(0kb) but no PNG images, but the folder "mouse" has PNG images

So excuse me, is there any way you can fix the bug?

Julian

**Comment by juliarnWu** [comment]
Dear Waka, I look forward to your next version of the work and wish it to be born sooner.

**Comment by valelu** [comment]
The IEEE warnings are from Fortran and thus depend on local Fortran installations. The loops are not infinite and the Fortran warnings cease when the Green functions calculations are finished.

**Comment by jborges1755** [comment]
When I run the the  example_2_SAC.py", I get the following error:

python example_2_SAC.py
Traceback (most recent call last):
  File "/Users/jborges/TRABALHO/PROGRAMAS/BayesISOLA-master/example_2_SAC.py", line 27, in <module>
    data = BayesISOLA.process_data(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jborges/TRABALHO/PROGRAMAS/BayesISOLA-master/BayesISOLA/process_data.py", line 104, in __init__
    self.set_parameters(fmax, fmin, min_depth)
  File "/Users/jborges/TRABALHO/PROGRAMAS/BayesISOLA-master/BayesISOLA/_parameters.py", line 165, in set_parameters
    self.set_working_sampling()
  File "/Users/jborges/TRABALHO/PROGRAMAS/BayesISOLA-master/BayesISOLA/_parameters.py", line 41, in set_working_sampling
    SAMPRATE = 1. / lcmm(*self.d.data_deltas) # kazda stanice muze mit jine vzorkovani, bereme nejvetsiho spolecneho delitele (= 1. / nejmensi spolecny nasobek)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jborges/TRABALHO/PROGRAMAS/BayesISOLA-master/BayesISOLA/helpers.py", line 48, in lcmm
    b = fractions.gcd(a, b)
        ^^^^^^^^^^^^^
AttributeError: module 'fractions' has no attribute 'gcd'

 I kindly ask for your help in solving this problem. 
Thank you very much, 

jborges.

**Comment by andresp-wave** [comment]
A bit late but you can change the package fractions to math and that should work.
